### ISSUE TITLE
implement adding an NFT avatar

### ISSUE THREAD

**Issue by estebanabaroa** [plebbit/seedit#142]
can use a similar UI and code as plebbit-react

**Comment by plebeius-eth** [comment]
4b902871b92043920e3cff64536d88af53cb4ad2


![Image](https://github.com/plebbit/seedit/assets/117766773/58a521cd-1a75-4b7f-a7d7-2cbcddbca2d5)

**Comment by estebanabaroa** [comment]
missing button to edit, and shouldnt show error if no avatar is set
