### ISSUE TITLE
fix topbar "MORE" button should not cover the sub list

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#156]
The last sub in the list gets covered by the "MORE" button. Instead, the list should end before the button.

![Image](https://github.com/plebbit/seedit/assets/117766773/4f14136b-8534-40e7-9cdd-101b188ae7d8)

**Comment by estebanabaroa** [comment]
>Instead, the list should end before the button.

I disagree, if you end before the user won't know it's scrollable, and we'll have a hole

**Comment by plebeius-eth** [comment]
> > Instead, the list should end before the button.
> 
> I disagree, if you end before the user won't know it's scrollable, and we'll have a hole

it didn't change look, there's no hole. Simply the list ends before the button, at the end of the list. Fixed: ce3ed1447ef71fe1b4f49f6f80898e879d469f74


![Image](https://github.com/plebbit/seedit/assets/117766773/b7eb72dc-4dca-488e-85b0-93422bcfe6c2)



![Image](https://github.com/plebbit/seedit/assets/117766773/b4ac961d-a64a-49c2-8326-7eee6d275095)

**Comment by estebanabaroa** [comment]
> there's no hole

yes there's a hole, the size of the hole depends on the width of your screen.

also now since it ends cleanly, the user doesn't know it's scrollable.

all websites with horizontally scrollable menus cut them off, that's how you indicate to users that it's scrollable.

**Comment by plebeius-eth** [comment]
>yes there's a hole, the size of the hole depends on the width of your screen.

Ah I see, that hole is actually unrelated to this issue, it's been present since the beginning (you can check seedit.eth.limo) and I added it to make it look exactly like old.reddit, which has it, so I don't think we should remove it, also because it looks good. I'm hiding it with a media query on mobile because we need space on mobile.

>also now since it ends cleanly, the user doesn't know it's scrollable.

The user does know it's scrollable: the list only ends cleanly at its end after scrolling, just like it starts cleanly at its beginning before scrolling. It's cut off to the right before scrolling, and it's cut off to the left after scrolling all the way to its end. 

> it's not a bug

The bug described by this issue refers to the last sub address at the end of the list, which should be visible, just like the first element of the list ("home" button) is visible at the beginning of the list. The bug is not the list being cut off, that's still happening in both ends of the list. It's fixed on https://seedit.netlify.app

**Comment by estebanabaroa** [comment]
> The user does know it's scrollable: the list only ends cleanly at its end after scrolling, just like it starts cleanly at its beginning before scrolling. It's cut off to the right before scrolling, and it's cut off to the left after scrolling all the way to its end.

oh my bad I guess I didnt understand the issue at all
