### ISSUE TITLE
add moderator edit reasons

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#170]
>I'd just add it like people do it manually on reddit, ie
```
<comment.content>
Edit: <comment.reason>
```
>maybe we add edit time and a (show original) button, not sure

**Comment by plebeius-eth** [comment]
dd6744ab7003792c1c66daf60b43731f068d1562

**Comment by plebeius-eth** [comment]
![Image](https://github.com/plebbit/seedit/assets/117766773/ef73270d-d39e-4e4d-bed8-56fe53c2e7d8)



![Image](https://github.com/plebbit/seedit/assets/117766773/d702ec42-09c0-4ee6-85c2-ecaac90e475f)

**Comment by estebanabaroa** [comment]
icon looks bad imo, I would just do it as text, dont think it matters that people can put fake mod reasons for now

**Comment by plebeius-eth** [comment]
> icon looks bad imo, I would just do it as text, dont think it matters that people can put fake mod reasons for now

yes I agree actually, reverted already 911e4cf0d83e64953a6ad40a6c76a06f936a8500
