### ISSUE TITLE
fix changing the sort type shouldn't change the time filter

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#172]
>for example when you click HOME or ALL, or change the sort type, or change the filter type, it should keep the same sort type and filter you're already on
there's no easy way to implement that but you can check how I did it in plebones

**Comment by plebeius-eth** [comment]
e2de55987cc02ecee94a0c57c4954d31a478ef27
da75c6978a99609cf999ad92958d2ec57c60ea5f

**Comment by estebanabaroa** [comment]
can't use useEffect to setState, it causes useless rerenders and slows down the app

**Comment by plebeius-eth** [comment]
updated ce32277f97f44eb3ac6a77c3521f7d9eac5baaf8

**Comment by plebeius-eth** [comment]
updated ce32277f97f44eb3ac6a77c3521f7d9eac5baaf8
