### ISSUE TITLE
add button in posts to quickly subscribe to subs in p/all

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#229]
this + button that turns green on hover, and a green checkmark when clicked

![Image](https://github.com/plebbit/seedit/assets/117766773/c11ab372-8f32-42ca-aab0-5d35e236ed6d)

**Comment by plebeius-eth** [comment]
569973947cc21a54ed2c43896d93aed843d52062
1px higher than on reddit to center it

**Comment by estebanabaroa** [comment]
not centered properly imo
