### ISSUE TITLE
add nft profile pictures to posts, replies and author sidebar

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#231]
>I think we can test it in the post card for a while and see if its annoying or not

**Comment by plebeius-eth** [comment]
14c2cec5650e444ddf6db254b7c9232298114534

![Image](https://github.com/plebbit/seedit/assets/117766773/800e5803-a208-45eb-a233-0c0f39084242)
![Image](https://github.com/plebbit/seedit/assets/117766773/ec9e40d0-2ca9-46ab-b40a-b8f7316162de)
![Image](https://github.com/plebbit/seedit/assets/117766773/bd772072-9e1c-4dce-980b-4dc4dc13e7d8)

**Comment by estebanabaroa** [comment]
need to wait until we test the real nfts until we close this issue

**Comment by plebeius-eth** [comment]
should be complete now ae4bb58c999eda1e3575b45881e08d45bf5905ac
