### ISSUE TITLE
implement banning accounts for communities

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#253]
Community admins should be able to prevent certain accounts from posting in their community.

**Comment by estebanabaroa** [comment]
should include a time amount, probably in days

**Comment by plebeius-eth** [comment]
22beb4e0ea6a2c300422fa8a21b5f230af985ec0

**Comment by estebanabaroa** [comment]
looks bad I would do max width 30px
![image](https://github.com/plebbit/seedit/assets/90033261/cc248b6a-e600-44ac-9460-dd477f89823c)

30px:
![image](https://github.com/plebbit/seedit/assets/90033261/57784287-5ee5-4f3b-8c4c-2f6c0e06be94)

**Comment by plebeius-eth** [comment]
so apparently Firefox/gecko doesn't adjust the width of the input based on the `max={}` attribute, while chromium and webkit do. I set it to three digits which I think it's best, so mods can do 365 or 99999 and the number can scroll horizontally. Fixed it with Firefox-specific CSS.
