### ISSUE TITLE
add locked state for posts that are removed or deleted, with banner, hiding reply form

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#282]
Posts that are removed or deleted cannot be replied to, and the UI should reflect this.

**Comment by plebeius-eth** [comment]
2490bc35f452e2231afea94edac14a9280bf430d
actually I think the reply form should stay, like on old reddit

![Image](https://github.com/plebbit/seedit/assets/117766773/92e80161-5bad-4687-a36e-01d22d0a2ba6)

**Comment by estebanabaroa** [comment]
interestingly reddit lets you comment on removed posts, but plebbit doesnt. we should probably show "This post is ${state}. You won't be able to comment." It shouldn't say "locked" if a post is deleted and not locked.

![image](https://github.com/plebbit/seedit/assets/90033261/0c0e33dd-9a4b-4ede-a548-01f1332e6e6e)

**Comment by plebeius-eth** [comment]
should be fixed now: 7f6f0dd7fbf86b4736e4607954778ed2c69893b3
