### ISSUE TITLE
disable some comment tools for failed or pending comments

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#283]
Many buttons can't work if a post is removed, deleted or failed. For example, the permalink button can't work for a failed post since it has no cid.

**Comment by plebeius-eth** [comment]
d6778a73f8c7a27ab018ccff102e4b14a7116771
6e341e33fc5b57dae7eb7d6858a5159e20e054d6

**Comment by plebeius-eth** [comment]
they are not hidden, they are disabled

**Comment by estebanabaroa** [comment]
its possible to share a deleted/removed post, it's also possible to undelete a post, so the comment tool should still be there, it only makes sense to remove it for failed

**Comment by plebeius-eth** [comment]
the title of this issue was wrong, actually I only ended up disabling the tools for pending or failed posts, checking for the cid. You can already share or edit a removed/deleted comment
