### ISSUE TITLE
use query string for context route

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#284]
>`p/<sub>/c/<cid>` is part of the protocol, the /context isn't
so ideally we would have a way to do it without adding unnecessary endpoints to the protocol
Im actually not a fan of using /context endpoint
at all
cause it wont work on other clients
maybe it should be ?context=1 or something
this way those links will work in any client
and the previewer could potentially pass query string like ?context=1 to the app
this will make the links work on all clients, but the seedit client specifically can check the context query string and do something extra
cause `p/<sub>/c/<cid>/context` will 404 on plebchan and plebones which isnt cool
but `p/<sub>/c/<cid>?context=1` will work on all clients

**Comment by plebeius-eth** [comment]
6516245abfd2a0a02ac49628873265b7c9b5c0a3

**Comment by plebeius-eth** [comment]
>actually I realized I can't allow any query string because people can get around my caching and waste the previewer resources
>I could allow context: 1,2 or 3

>Im thinking maybe 1-5 would be useful

>I thought showing the full thread from the first level reply would be better, but actually no, they could be too large. I'm making it like reddit, default to 3 and able to change manually via the url
>ah because of this I'll only allow context 1-5, default to 3 for the button

**Comment by plebeius-eth** [comment]
b9d050c87c45b2e1c541a4ac45e7f23b6e5490f7

**Comment by estebanabaroa** [comment]
Im still seeing context=1, shouldnt it be context=3 like on reddit?

**Comment by plebeius-eth** [comment]
yes I forgot, changed it to 3 now 29891a6e39f7c7dd5f6e930f7f7f041126565fde
