### ISSUE TITLE
add 'loading comments' string in post view, hide reply form before comment is loaded

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#285]
>I think “all comments” should say “loading comments…”

>not a bad idea, maybe with the ellipsis animation

>Esteban Abaroa, [Mar 4, 2024 at 9:22:30 PM]:
you might want to remove the comment box before the comment is loaded, but keep it while the comment update is loading
imo its confusing to see the empty values with the comment box

**Comment by plebeius-eth** [comment]
a06869196d236f51ab8bfffae46bdf08aefd95df

**Comment by estebanabaroa** [comment]
I don't really like the fact that it shows "loading comments..." before the post data is loaded. maybe before the post data is loaded, we just hide the entire comment section, "all comments", "sort by", etc

then maybe once the post data is loaded (post.timestamp is defined), show the "loading comments..."

also the location of the state string is ugly imo:
![image](https://github.com/plebbit/seedit/assets/90033261/66ebc33f-8b14-472e-bfc6-a958e53b6ab8)

also another issue is that it is possible to comment before the comments load, so why remove the comment box. as soon post.subplebbitAddress and post.cid are defined, it's possible to write a comment.

**Comment by plebeius-eth** [comment]
fixed: e276763a3d0370242ae20d2a04ae17d0f5ddccb5
- the whole reply area appears as soon as timestamp is defined
- the reply form appears as soon as subplebbitAddress and cid are defined
- 'loading comments' disappears as soon as replyCount is defined
- state string has padding on top, it's closer to the replies area

**Comment by estebanabaroa** [comment]
no loading string before comment is loaded
![image](https://github.com/plebbit/seedit/assets/90033261/c50573a9-8e50-423a-a876-e4ee77de0842)

**Comment by estebanabaroa** [comment]
also I think I would remove the ellipsis animation from loading comments... it looks bad to have 2 ellipsis animations at once.

**Comment by plebeius-eth** [comment]
e1a3745af9e4b160acdf8d0d557ccf2f694038c8

**Comment by estebanabaroa** [comment]
there's a big empty space before the state string and 

also the comment update state string doesnt appear right away, there's like a 1 second lag. https://seedit.netlify.app/#/p/redditdeath.sol/c/QmatyFJHBk2DsCv6LCNbV8qXvPYtqTwyCVzBPGboXy99yk there's no lag on plebones https://plebones.netlify.app/#/p/redditdeath.sol/c/QmatyFJHBk2DsCv6LCNbV8qXvPYtqTwyCVzBPGboXy99yk

![image](https://github.com/plebbit/seedit/assets/90033261/3477e183-de79-4cf1-9a14-42b0e05fb517)

**Comment by plebeius-eth** [comment]
> there's a big empty space before the state string and
> 
> also the comment update state string doesnt appear right away, there's like a 1 second lag. https://seedit.netlify.app/#/p/redditdeath.sol/c/QmatyFJHBk2DsCv6LCNbV8qXvPYtqTwyCVzBPGboXy99yk there's no lag on plebones https://plebones.netlify.app/#/p/redditdeath.sol/c/QmatyFJHBk2DsCv6LCNbV8qXvPYtqTwyCVzBPGboXy99yk

should be fixed now f40665dc5cec28cdc859c5dc1f83f1aa6adecb1c

**Comment by estebanabaroa** [comment]
I think loading comments... should have an ellipsis, just not an animated ellipsis, because having 2 animations at the same time looks bad.

**Comment by plebeius-eth** [comment]
> I think loading comments... should have an ellipsis, just not an animated ellipsis, because having 2 animations at the same time looks bad.

yes that's better, fixed it b84e0fcba1f4539c4298774905822dac96b449e0
