### ISSUE TITLE
add redirect to link with hash on first app load

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#286]
>it's intended only for the homepage, for the sub link I meant it makes it more likely that users will know about the hash, because they will always see it in the homepage

>Esteban Abaroa, [Mar 4, 2024 at 6:23:01 PM]:
not sure, it has downsides, people will always share the app with /# which looks ugly
the upside is you wont forget to add the /#/ when typing in a url

>Tom (plebeius.eth), [Mar 4, 2024 at 6:23:41 PM (Mar 4, 2024 at 6:23:52 PM)]:
mmh ok I think that's a net positive

**Comment by plebeius-eth** [comment]
365b40d3626a40131b7b0d722a3d9e0e6ab9359b

**Comment by estebanabaroa** [comment]
```
 useEffect(() => {
    if (!window.location.hash && !isElectron) {
      // Calculate the base URL (protocol + host)
      const baseURL = window.location.protocol + '//' + window.location.host + '/';
      // Redirect to the base URL with `#/`
      window.location.replace(baseURL + '#/');
    }
  }, []);
  ```
  
that won't work if the site is served in a folder, like for example ipfs.io/ipfs/<cid>

it also will remove any query string unnecessarily which something else might need eventually and nobody will understand why
  
I don't think you should be messing with this, not worth it, it's non standard and has unexpected side effects. But if you insist on having it, the correct way to do it would be
```
useEffect(() => {
  if (!window.location.hash) {
    window.location.hash = '/'
  }
}, [])
```

**Comment by plebeius-eth** [comment]
I agree, doesn't seem worth it
