### ISSUE TITLE
implement adding wallets

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#288]

**Comment by plebeius-eth** [comment]
75b25e74cd6dba73aae7b3385669c5a80b2c2c75

**Comment by estebanabaroa** [comment]
made a mistake in plebones, the signature doesn't contain the wallet address, only the plebbit author address https://github.com/plebbit/plebones/commit/0c779bf7a79f27fafcfa465b7627aff242d6e727

**Comment by plebeius-eth** [comment]
fixed c45d2d3e8c551817fff896d1712a4e500e32d924
