### ISSUE TITLE
improve avatar settings design

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#323]
it's not good to hide the settings completely, the user doesn't know where to click, and expanded settings should have their own box design like the wallet one

**Comment by plebeius-eth** [comment]
cb85234ae8a5d84e7a9263d208d8eb36c379688f

**Comment by estebanabaroa** [comment]
> the user doesn't know where to click

I dont see how the user would not know where to click when clicking the profile pic is how you edit a profile pic on all other apps in existence

**Comment by plebeius-eth** [comment]
>I dont see how the user would not know where to click when clicking the profile pic is how you edit a profile pic on all other apps in existence

that's true actually, reverted the change. Closing as not planned

**Comment by estebanabaroa** [comment]
wasnt there a + add avatar button or something? that was better than just nothing

**Comment by plebeius-eth** [comment]
89bcbaf78e6d6a1edd4a836e69a01fef3b73e835

**Comment by estebanabaroa** [comment]
not possible to change an nft already added, clicking the avatar doesnt open it. the original design was fine btw I think, not sure why you changed it.

**Comment by plebeius-eth** [comment]
0c31ba59c5d493203b7bd5e87b4bee5613b63155
should be fixed now
