### ISSUE TITLE
implement usePlebbitRpcSettings

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#335]
in the subplebbit settings/create page, usePlebbitRpcSettings should be used to display the challenges in the challenges setting, instead of hardcoding the challenges. When creating a new sub, the default challenge should be displayed as set automatically.

**Comment by plebeius-eth** [comment]
52cf63a497fd5131e3b50d8af7fcf8a6ef61eb7d
ea7853be63a9f7604ce579d7469ad09885b2ebc8

**Comment by plebeius-eth** [comment]
fixed ad7a8936cb158a934b53e012bc7741641edcdf0b

**Comment by estebanabaroa** [comment]
seems like the challenge names are still hard coded? https://github.com/plebbit/seedit/blob/ad7a8936cb158a934b53e012bc7741641edcdf0b/src/views/subplebbit/subplebbit-settings/subplebbit-settings.tsx#L358

everything should come from the plebbit-rpc, nothing should be hard coded. even the default recommended challenge should probably not be hard coded, because the rpc will not necessarily support a challenge named 'captcha-canvas-v3'. can you make the UI work without a default recommended challenge?

**Comment by estebanabaroa** [comment]
also you shouldnt hardcode the default challenge options like https://github.com/plebbit/seedit/blob/ad7a8936cb158a934b53e012bc7741641edcdf0b/src/views/subplebbit/subplebbit-settings/subplebbit-settings.tsx#L930

it's possible that the rpc has a challenge called 'captcha-canvas-v3' but with different options. if you want to use default challenge options you can use the default values provided by `optionInputs` if any.

**Comment by plebeius-eth** [comment]
654b4277d8dfc91b8501eaffd3549c1580f72fa7

I removed all hardcodes, creating and editing subs should work, including changing/customizing the challenge.

also added a "loading..." string before rendering anything, while subplebbit.createdAt is undefined (in the subplebbit settings page)

in the create subplebbit page, i'm not showing the challenges field, because it doesn't seem to work when creating a sub. The createSubplebbit() hook doesn't respond if I also specify a challenge. This is not a big issue though, I think 99% of users willing to create a sub don't want to go over the challenge settings right away, I think they'll find them intimidating. 

usePlebbitRpcSettings() takes a long time to initialize sometimes, it doesn't update by itself, I have to refresh the page to initialize and it often doesn't work. I guess it's a bug specific to it. You can see this from the <select> element in the challenge settings, sometimes it won't load anything until you refresh.
