### ISSUE TITLE
add 'own communities' button in topbar dropdown

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#341]

**Comment by plebeius-eth** [comment]
0cf89c2d39f52a9474e0853ebbe1b9dbc5361efd

**Comment by estebanabaroa** [comment]
I dont think "Own Community" sounds good, it sounds weird. Rather I would link to "My communities" and link to this page https://seedit.netlify.app/#/communities so the user can quickly see all the communities hes a mod in

**Comment by plebeius-eth** [comment]
agreed, fixed d21609d9d0f359fec655f220e29b30947f296696
