### ISSUE TITLE
fix search bar allows to connect to a sub address without a tld

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#349]
it should check if the address is either a valid IPNS public key or contains a dot (for the tld), and no spaces or slashes

**Comment by plebeius-eth** [comment]
f4798f304c52572495dc64d8ce7d495b676e170f

**Comment by estebanabaroa** [comment]
you should not validate the domain, plebbit-js already validates it. otherwise you'll have to change the validate code any time we add a new domain or new key

**Comment by plebeius-eth** [comment]
a40442d785eed15563dd9865e5bdd1720d80aee8

removed the validation checks and displaying the error message

![Image](https://github.com/plebbit/seedit/assets/117766773/a436ec21-ada9-42d9-bec1-c84fcf4dc1a2)
