### ISSUE TITLE
add specific nsfw tag filtering with "show nsfw content" settings, post nsfw labels

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#352]
https://t.me/seeditreact/6562

**Comment by plebeius-eth** [comment]
![Image](https://github.com/user-attachments/assets/549ef68a-cf98-4db0-9e6a-540b2c9d28ac)

**Comment by plebeius-eth** [comment]
95d10a3719ac9d165ba376cb965edba658f338bf
a0d119c580c56dd5eb7d559d297d4b7f6643523f
5a078e772de0fcd7e91f2f220771cbf1ece16e9b

**Comment by estebanabaroa** [comment]
how do I test this?

**Comment by plebeius-eth** [comment]
> how do I test this?

dm'd link on tg
