### ISSUE TITLE
add: alert user to lower time filter if there aren't enough posts

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#370]
https://t.me/seeditreact/6714

**Comment by plebeius-eth** [comment]
35febb2ee25c1b5e1603d657b743d7492b57a262
aa1de99b5a2275b03637eec92186af10375d6ec0

**Comment by estebanabaroa** [comment]
Im not seeing it

![image](https://github.com/user-attachments/assets/4313caaa-a237-45be-ae29-28a99ffe18c8)

**Comment by plebeius-eth** [comment]
updated p/all c148cbce5db2e7327eb659f9fecb4976a582cdd7

**Comment by estebanabaroa** [comment]
![image](https://github.com/user-attachments/assets/bb48e1c8-a566-4235-928c-a03f57e54433)

I dont really like how the state string has the same design.

maybe something like this would be better

![image](https://github.com/user-attachments/assets/3031018a-fa8d-4f63-be8e-5145cce0ccc5)

or like this

![image](https://github.com/user-attachments/assets/48018197-477c-4ccb-a958-ca3c1820cee1)

**Comment by plebeius-eth** [comment]
the yellow bar should only be at the top of the feed, so we can't do that

the pagination on old reddit looks very good, we should use that design for sure

**Comment by plebeius-eth** [comment]
e5fd22488f05e76d03aa5dbb04bd1b366680c8df

![Image](https://github.com/user-attachments/assets/e03a097e-411d-40d7-8c0a-e9de751dff3f)
