### ISSUE TITLE
add: info about account being stored locally and post history not being synced

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#384]
Some users have complained about the account post history not being synced across clients, while using the same account file with each client. The account settings should specify that accounts can't be synced yet, and they are stored locally in the  website's local storage.

**Comment by plebeius-eth** [comment]
I think it should say "warning: the account is stored locally in this specific app ({storageLocation}) and the post history cannot yet be synced with other clients" where storageLocation is either the web client hostname, "this desktop app" for the electron client and "this mobile app" for the APK.

**Comment by plebeius-eth** [comment]
d328c5c2772050a523e3485b3c31153edd1d08e7
7d0d00168082d14dd9c1b735dbd86c31d8fff889

**Comment by estebanabaroa** [comment]
99.99% of users dont want to see this message. They either already know, or don't care. Why are we making the site worse for 99.99% of users, to make it better for 0.01% of users
