### ISSUE TITLE
fix: some links are embedded as videos but they are webpages or images

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#385]
looks like ext-name is bugged 

cryptoserious.eth/c/QmVFbPMmPQAobLLUvrpLPFtcLMQTQZJGM6JwdgQym13fKu

**Comment by plebeius-eth** [comment]
18b5a8e6b5576770c8b2435348acb3e8a5de33d8

**Comment by estebanabaroa** [comment]
doing `new URL()` isn't free, it wastes ms, which makes the feed lag when you scroll, you shouldnt do it over and over. you should do it once per post maximum
