### ISSUE TITLE
add: client-side thumbnail fetching from websites with CORS access

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#386]
A user reported a missing thumbnail from a link to his website, which has CORS access: https://pleb.bz/p/plebpiracy.eth/c/QmSTx9pX1Ttk5tKfs6EJQk5sonXckjNwF2srBbhFHPKKKv

most sites don't have CORS access because it's a security risk, but it's cool to enable client-side thumbnail fetching for those who do I guess. Subplebbits have thumbnail fetching turned off by default because it leaks the plebbit node IP address.

**Comment by plebeius-eth** [comment]
b3bbb9c04d88a75d2956d606a8023bf6120964e9

**Comment by estebanabaroa** [comment]
we use this library for getting the thumbnail in the subplebbit, dont think it works in the browser but there might be other fallbacks than just doing const ogImage = doc.querySelector('meta[property="og:image"]');

https://www.npmjs.com/package/open-graph-scraper
https://github.com/jshemas/openGraphScraper/blob/master/lib/extract.ts

not super high priority but something to think about
