### ISSUE TITLE
add: caching to first frame of gifs so they don't reload all the time

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#392]
the first frame of the gifs has to be cached otherwise it will reload all the time when navigating

**Comment by plebeius-eth** [comment]
e1c02cdf8f60c9373c87f0fdac0b40d31e9255d1

**Comment by estebanabaroa** [comment]
cant use local storage for cache

**Comment by plebeius-eth** [comment]
fixed 9273c0f5d73e93a35b18dbf7ccfaa1f5529becdc
