### ISSUE TITLE
fix: profile info banner should disappear after 3 visits, not just one

### ISSUE THREAD

**Issue by plebeius-eth** [plebbit/seedit#458]
Currently, this banner disappears after just 1 visit, so it's too ephemeral. It should probably disappear after 3 visits. It also needs an X to close it at any time. Closable info banners are not found on old reddit, but they are a very common UI element, so it shouldn't be an issue to have them.

**Comment by estebanabaroa** [comment]
maybe it should just be a regular `×` (multiplication sign)

also it probably shouldnt change color on hover, that's not very reddit like. reddit links usually underline or do nothing when you hover them. I think the x should probably not hover.

**Comment by plebeius-eth** [comment]
changed it to that, it looks better

![Image](https://github.com/user-attachments/assets/06eab7a8-8ab1-4a13-a448-d24e702d75d2)
![Image](https://github.com/user-attachments/assets/0bbe57ce-9bd3-4054-9130-371045e38230)


989b7bdae355605c1f322dde56351f2ae1e5082e
